// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uprqlksrigxxbmmwqepv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVwcnFsa3NyaWd4eGJtbXdxZXB2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYyODg1MjUsImV4cCI6MjA5MTg2NDUyNX0.O4ngTDRCCjxfR_rI74XdhbOG2Vqrf-lQDduN1yJLx5U";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
